binderhub:
  config:
    BinderHub:
      use_registry: false
      hub_url: "http://nb-192-46-238-56.frankfurt.nodebalancer.linode.com/"

  service:
    type: ClusterIP

  jupyterhub:
    debug:
      enabled: true
    hub:
      services:
        binder:
          url: "http://10.128.147.158"
          apiToken: "6e5252a4ef9f19554cfffd970270e144e4dcca1520b9c6bb6c6f412743cbea7a"
          oauth_redirect_uri: "http://nb-192-46-238-56.frankfurt.nodebalancer.linode.com//oauth_callback"
          oauth_client_id: "binder-oauth-client-test"
      config:
        JupyterHub:
          authenticator_class: dummy

    proxy:
      secretToken: "29195074ffd6cae79ed3dcb7483f65c098275b172a4757cc998c00dcc63ff173"
      https:
        enabled: false
      service:
        type: ClusterIP

    config:
      Authenticator:
        admin_users: ['admin']
